import { GAME_TERM_DETAILS, type GameTermDetail } from './gameTermDetails';

/**
 * Search labels and rule references for the core rulebook's Part 11 glossary.
 * `source.printedPage` is the page number printed in the English rulebook, not
 * the PDF viewer's page index. The final entries add frequently needed basic
 * concepts defined elsewhere in the same rulebook.
 */
export interface GameTerm {
  id: string;
  name: { es: string; en: string };
  aliases?: { es: string[]; en: string[] };
  summary: { es: string; en: string };
  details: GameTermDetail;
  category: string;
  phaseIds?: string[];
  source: { section: string; printedPage: number; printedEndPage?: number; faqPage?: number };
  relatedIds?: string[];
}

type LocalizedText = { es: string; en: string };

function term(
  id: string,
  printedPage: number,
  category: string,
  phaseIds: string[],
  name: LocalizedText,
  summary: LocalizedText,
  options: { aliases?: { es: string[]; en: string[] }; relatedIds?: string[]; section?: string; printedEndPage?: number; faqPage?: number } = {},
): GameTerm {
  const details = GAME_TERM_DETAILS[id];
  if (!details) throw new Error(`Missing rule details for game term: ${id}`);
  return {
    id, name, summary, details, category, phaseIds,
    source: { section: options.section ?? '11', printedPage, ...(options.printedEndPage ? { printedEndPage: options.printedEndPage } : {}), ...(options.faqPage ? { faqPage: options.faqPage } : {}) },
    ...(options.aliases ? { aliases: options.aliases } : {}),
    ...(options.relatedIds ? { relatedIds: options.relatedIds } : {}),
  };
}

export const GAME_TERMS: readonly GameTerm[] = [
  term('access-point', 82, 'terrain', ['movement'],
    { en: 'ACCESS POINT', es: 'Punto de acceso' },
    { en: 'A connection in terrain through which models can change elevation while moving.', es: 'Conexión del terreno por la que las miniaturas pueden cambiar de nivel de elevación al moverse.' },
    { aliases: { en: ['access points'], es: ['acceso'] }, relatedIds: ['elevation-level'] }),
  term('active-player', 82, 'core', ['core-concepts'],
    { en: 'ACTIVE PLAYER', es: 'Jugador activo' },
    { en: 'The player currently taking a turn to act during alternating activations.', es: 'El jugador al que le toca actuar durante las activaciones alternas.' },
    { relatedIds: ['activation', 'pass'] }),
  term('anti-evade', 82, 'weapons', ['assault', 'combat'],
    { en: 'ANTI-EVADE (X)', es: 'ANTI-EVADE (X)' },
    { en: 'An enemy attacked with this weapon suffers a -X modifier to its Evade roll for that attack.', es: 'El enemigo atacado con esta arma sufre un modificador de -X en su tirada de Evasión para ese ataque.' },
    { aliases: { en: ['anti evade'], es: ['antievasión'] }, relatedIds: ['evade-roll'] }),
  term('army-slot', 82, 'army', ['before-play'],
    { en: 'ARMY SLOT', es: 'Espacio de ejército' },
    { en: 'A Core, Elite, Support, Air or Hero allowance used when building an army. A unit occupies as many matching slots as its starting Supply Value.', es: 'Cupo de tipo Básica, Élite, Apoyo, Aérea o Héroe usado para crear la lista. Una unidad ocupa tantos espacios de su tipo como su Suministro inicial.' },
    { relatedIds: ['supply-value', 'faction-tags'] }),
  term('available-supply', 82, 'army', ['movement'],
    { en: 'AVAILABLE SUPPLY', es: 'Suministro disponible' },
    { en: 'Supply Pool minus the Current Supply of friendly units on the battlefield; a reserve unit needs at least its own Current Supply available to deploy.', es: 'Reserva de Suministro menos el Suministro Actual de las unidades amigas en mesa; para desplegar desde Reservas debe caber el Suministro Actual de esa unidad.' },
    { relatedIds: ['supply-pool', 'current-supply-value', 'reserves'] }),
  term('blocking-terrain', 82, 'terrain', ['core-concepts', 'assault'],
    { en: 'BLOCKING TERRAIN', es: 'Terreno bloqueante' },
    { en: 'Terrain of Effective Size 1 or more. Whether it blocks sight depends on cover rules; movement through it is checked separately.', es: 'Terreno de Tamaño Efectivo 1 o más. Las reglas de cobertura determinan si bloquea la visión; su paso se comprueba por separado.' },
    { relatedIds: ['effective-size', 'line-of-sight'] }),
  term('buff', 82, 'status', ['core-concepts'],
    { en: 'BUFF [Characteristic] (X)', es: 'BUFF [Característica] (X)' },
    { en: 'Until round end, improves a characteristic by X: lowers a target number or raises a numerical value.', es: 'Hasta el final de la ronda mejora una característica en X: baja un valor objetivo o aumenta un valor numérico.' },
    { aliases: { en: ['buff'], es: ['bonificación'] }, relatedIds: ['debuff', 'modifier'] }),
  term('bulky', 82, 'weapons', ['assault'],
    { en: 'BULKY', es: 'BULKY' },
    { en: 'A weapon that cannot make a ranged attack while its unit is Engaged.', es: 'Arma que no puede disparar mientras su unidad está trabada.' },
    { aliases: { en: [], es: ['voluminosa'] }, relatedIds: ['engaged'] }),
  term('burrowed', 82, 'status', ['movement', 'combat', 'scoring-cleanup'],
    { en: 'BURROWED', es: 'BURROWED' },
    { en: 'A status that grants HIDDEN and Size 0, prevents objective control and limits actions. Most allowed actions remove BURROWED immediately; it can Evade every attack.', es: 'Estado que da HIDDEN y Tamaño 0, impide controlar objetivos y limita las acciones. Casi todas las acciones permitidas lo retiran de inmediato; permite Evasión ante cada ataque.' },
    { aliases: { en: ['burrow'], es: ['enterrada', 'enterrado'] }, relatedIds: ['hidden', 'mission-markers'], printedEndPage: 83 }),
  term('burst-fire', 83, 'weapons', ['assault'],
    { en: 'BURST FIRE Y” (X)', es: 'BURST FIRE Y” (X)' },
    { en: 'Against a target within Y inches of the firing model, this weapon gains X Rate of Attack for that attack.', es: 'Contra un objetivo a Y pulgadas o menos de la miniatura atacante, esta arma gana X de Cadencia de Ataque en ese ataque.' },
    { aliases: { en: ['burst fire'], es: ['ráfaga'] } }),
  term('combat-tags', 83, 'core', ['core-concepts', 'assault'],
    { en: 'COMBAT TAGS', es: 'Etiquetas de combate' },
    { en: 'Unit descriptors such as Ground, Flying, Biological and Armoured; they govern targeting, Surge and some ability effects.', es: 'Descriptores de unidad como Terrestre, Voladora, Biológica y Blindada; intervienen en objetivos válidos, Surge y algunas habilidades.' },
    { relatedIds: ['faction-tags', 'surge'] }),
  term('concentrated-fire', 83, 'weapons', ['assault', 'combat'],
    { en: 'CONCENTRATED FIRE (X)', es: 'CONCENTRATED FIRE (X)' },
    { en: 'An attack with this weapon can remove at most X models; damage left after that limit is discarded.', es: 'Un ataque con esta arma puede retirar como máximo X miniaturas; el daño sobrante tras alcanzar ese límite se descarta.' },
    { aliases: { en: ['concentrated fire'], es: ['fuego concentrado'] } }),
  term('controlling-player', 83, 'core', ['core-concepts'],
    { en: 'CONTROLLING PLAYER', es: 'Jugador controlador' },
    { en: 'The player currently commanding a unit, model or token and making its decisions and rolls; control can change through an ability.', es: 'Quien dirige actualmente una unidad, miniatura o ficha y toma sus decisiones y tiradas; una habilidad puede transferir ese control.' },
    { relatedIds: ['active-player'] }),
  term('critical-hit', 83, 'weapons', ['assault', 'combat'],
    { en: 'CRITICAL HIT (X)', es: 'CRITICAL HIT (X)' },
    { en: 'Moves up to X dice from the Armour Pool straight to the Damage Pool, bypassing Armour.', es: 'Mueve hasta X dados de la Reserva de Armadura directamente a la de Daño, sin tirar Armadura.' },
    { aliases: { en: ['critical hit'], es: ['impacto crítico'] }, relatedIds: ['dodge'] }),
  term('current-supply-value', 83, 'army', ['movement', 'scoring-cleanup'],
    { en: 'CURRENT SUPPLY VALUE', es: 'Valor de Suministro Actual' },
    { en: 'The Supply Profile value for the unit’s present model count. Update it as soon as casualties move the unit to a lower bracket.', es: 'Valor del Perfil de Suministro correspondiente al número actual de miniaturas. Se actualiza en cuanto las bajas bajan a la unidad de tramo.' },
    { relatedIds: ['supply-value', 'available-supply'] }),
  term('debuff', 83, 'status', ['core-concepts'],
    { en: 'DEBUFF [Characteristic] (X)', es: 'DEBUFF [Característica] (X)' },
    { en: 'Until round end, worsens a characteristic by X: raises a target number or lowers a numerical value, never below zero.', es: 'Hasta el final de la ronda empeora una característica en X: sube un valor objetivo o reduce un valor numérico, nunca por debajo de cero.' },
    { aliases: { en: ['debuff'], es: ['penalización'] }, relatedIds: ['buff', 'modifier'] }),
  term('displacement', 83, 'abilities', ['movement', 'assault'],
    { en: 'DISPLACEMENT', es: 'DISPLACEMENT' },
    { en: 'Allows the Leading Model to finish a move overlapping the specified unit or token, which is then placed in base contact or as close as possible.', es: 'Permite a la Miniatura Líder acabar un movimiento solapando la unidad o ficha indicada, que después se coloca en contacto de peanas o lo más cerca posible.' },
    { aliases: { en: [], es: ['desplazamiento'] }, relatedIds: ['leading-model'] }),
  term('dodge', 84, 'status', ['assault', 'combat'],
    { en: 'DODGE (X)', es: 'DODGE (X)' },
    { en: 'When targeted, reduces by X the Armour Pool dice that Surge or CRITICAL HIT would send to the Damage Pool.', es: 'Cuando recibe un ataque, reduce en X los dados que Surge o CRITICAL HIT pasarían de Armadura a Daño.' },
    { aliases: { en: [], es: ['esquiva'] }, relatedIds: ['surge', 'critical-hit'] }),
  term('effective-size', 84, 'terrain', ['core-concepts', 'assault'],
    { en: 'EFFECTIVE SIZE', es: 'Tamaño efectivo' },
    { en: 'A model’s Size plus the Size of terrain it stands on; used mainly to check whether terrain blocks Line of Sight.', es: 'Tamaño de la miniatura más el del terreno donde está; se usa sobre todo para comprobar si un terreno bloquea la línea de visión.' },
    { relatedIds: ['blocking-terrain', 'elevation-level'] }),
  term('elevation-level', 84, 'terrain', ['movement', 'assault'],
    { en: 'ELEVATION LEVEL', es: 'Nivel de elevación' },
    { en: 'A model occupies Ground, Mid or High Ground according to where its base rests; if the base spans levels, use the highest one.', es: 'La peana determina si una miniatura está a nivel del suelo, medio o alto; si abarca varios niveles, se usa el más alto.' },
    { relatedIds: ['ground-level', 'mid-ground', 'high-ground'] }),
  term('enemy', 84, 'core', ['core-concepts'],
    { en: 'ENEMY', es: 'Enemigo' },
    { en: 'An opposing player’s units, tokens and cards. Friendly units cannot normally be chosen as attack targets.', es: 'Unidades, fichas y cartas del jugador contrario. Las unidades amigas normalmente no pueden elegirse como objetivo de un ataque.' },
    { relatedIds: ['friendly'] }),
  term('engaged', 84, 'combat', ['movement', 'assault', 'combat'],
    { en: 'ENGAGED', es: 'Trabada' },
    { en: 'A Ground unit with a model within 1 inch of an enemy Ground model, where terrain and elevation allow contact; the status restricts movement and shooting.', es: 'Unidad terrestre con una miniatura a 1 pulgada o menos de otra terrestre enemiga, siempre que terreno y altura permitan el enfrentamiento; limita movimiento y disparo.' },
    { aliases: { en: ['engagement'], es: ['trabado', 'en combate'] }, relatedIds: ['engagement-range', 'unengaged'] }),
  term('engagement-range', 84, 'combat', ['movement', 'assault', 'combat'],
    { en: 'ENGAGEMENT RANGE', es: 'Alcance de enfrentamiento' },
    { en: 'A horizontal 1-inch zone around a model’s base, used to determine engagement and melee reach.', es: 'Zona horizontal de 1 pulgada desde la peana, usada para determinar si hay trabamiento y alcance cuerpo a cuerpo.' },
    { relatedIds: ['engaged', 'fighting-rank'] }),
  term('entry-edge', 84, 'movement', ['movement'],
    { en: 'ENTRY EDGE', es: 'Borde de entrada' },
    { en: 'The table edge assigned by the Deployment Card through which units normally enter from Reserves.', es: 'Borde de mesa asignado por la Carta de Despliegue por el que normalmente entran las unidades desde Reservas.' },
    { relatedIds: ['reserves', 'zone-of-influence'] }),
  term('faction-tags', 84, 'army', ['before-play'],
    { en: 'FACTION TAGS', es: 'Etiquetas de facción' },
    { en: 'Race and subfaction labels used in army building; every tag on a unit or Tactical Card must appear on the chosen Faction Card.', es: 'Etiquetas de raza y subfacción usadas para crear la lista; todas las de una unidad o Carta Táctica deben figurar en la Carta de Facción elegida.' },
    { relatedIds: ['combat-tags', 'army-slot'] }),
  term('fighting-rank', 85, 'combat', ['combat'],
    { en: 'FIGHTING RANK', es: 'Fila de combate' },
    { en: 'Models within an enemy’s Engagement Range; they can strike with Combat Phase weapons.', es: 'Miniaturas dentro del Alcance de Enfrentamiento enemigo; pueden atacar con armas de la Fase de Combate.' },
    { relatedIds: ['supporting-rank', 'engagement-range'] }),
  term('first-player-marker', 85, 'core', ['before-play', 'movement', 'assault', 'scoring-cleanup'],
    { en: 'FIRST PLAYER MARKER', es: 'Marcador de primer jugador' },
    { en: 'Tracks initiative. Its holder chooses who acts first each phase; passing and end-of-round scoring can change its owner.', es: 'Señala la iniciativa. Quien lo tiene elige quién actúa primero en cada fase; pasar y la puntuación final de ronda pueden cambiar su dueño.' },
    { relatedIds: ['pass', 'victory-points'] }),
  term('flying', 85, 'movement', ['movement', 'assault', 'combat', 'scoring-cleanup'],
    { en: 'FLYING', es: 'Voladora' },
    { en: 'Ignores terrain when moving and is never Engaged, but cannot Charge, fight in the Combat Phase or contest Mission Markers.', es: 'Ignora el terreno al moverse y nunca queda trabada, pero no puede cargar, luchar en Combate ni disputar Marcadores de Misión.' },
    { aliases: { en: ['flying unit'], es: ['volador', 'unidad voladora'] }, relatedIds: ['engaged', 'mission-markers'] }),
  term('friendly', 85, 'core', ['core-concepts'],
    { en: 'FRIENDLY', es: 'Amigo' },
    { en: 'Your own and, in team games, your teammates’ units, tokens and cards.', es: 'Tus unidades, fichas y cartas y, en partidas por equipos, las de tus compañeros.' },
    { aliases: { en: ['ally'], es: ['amiga', 'aliado'] }, relatedIds: ['enemy'] }),
  term('grass', 85, 'terrain', ['movement', 'assault'],
    { en: 'GRASS', es: 'Hierba' },
    { en: 'Size 2 terrain that blocks sight but allows passage. Ground movement through it, or any unit ending on it, removes the piece permanently.', es: 'Terreno de Tamaño 2 que bloquea visión pero permite el paso. Atravesarlo con una unidad terrestre, o terminar encima con cualquier unidad, lo retira definitivamente.' },
    { relatedIds: ['blocking-terrain', 'flying'] }),
  term('ground-level', 85, 'terrain', ['movement', 'assault'],
    { en: 'GROUND LEVEL', es: 'Nivel del suelo' },
    { en: 'The elevation of a model whose base stands directly on the playmat; this is distinct from the Ground Combat Tag.', es: 'Elevación de una miniatura con la peana directamente sobre el tablero; no equivale a la etiqueta de combate Ground.' },
    { relatedIds: ['elevation-level', 'combat-tags'] }),
  term('heal', 86, 'abilities', ['core-concepts'],
    { en: 'HEAL (X)', es: 'HEAL (X)' },
    { en: 'Removes X accumulated damage from a unit, but cannot return destroyed models.', es: 'Retira X puntos de daño acumulado de la unidad, pero no devuelve miniaturas destruidas.' },
    { aliases: { en: ['healing'], es: ['curar', 'curación'] }, relatedIds: ['respawn'] }),
  term('hidden', 86, 'status', ['assault', 'combat'],
    { en: 'HIDDEN', es: 'HIDDEN' },
    { en: 'Cannot be targeted by ranged attacks or sight-dependent abilities from more than 4 inches; ignores IMPACT and may Evade every attack.', es: 'No puede recibir disparos ni habilidades que requieran visión desde más de 4 pulgadas; es inmune a IMPACT y puede Evadir cada ataque.' },
    { aliases: { en: ['concealed'], es: ['oculta', 'oculto'] }, relatedIds: ['impact', 'evade-roll'] }),
  term('high-ground', 86, 'terrain', ['movement', 'assault'],
    { en: 'HIGH GROUND', es: 'Terreno elevado' },
    { en: 'Elevation on horizontal Size 3+ terrain. Ground-level and High Ground models cannot engage directly; Mid Ground can connect them via Access Points.', es: 'Elevación sobre terreno horizontal de Tamaño 3 o más. No se enfrenta directamente con Nivel del Suelo; los Puntos de Acceso conectan con Nivel Medio.' },
    { relatedIds: ['elevation-level', 'access-point'] }),
  term('hits', 86, 'abilities', ['assault', 'combat'],
    { en: 'HITS X (Y)', es: 'HITS X (Y)' },
    { en: 'Inflicts X automatic hits directly in the Armour Pool, each with Damage Y and no Surge.', es: 'Inflige X impactos automáticos que entran en la Reserva de Armadura, cada uno con Daño Y y sin Surge.' },
    { aliases: { en: ['automatic hits'], es: ['impactos automáticos'] }, relatedIds: ['surge'] }),
  term('impact', 86, 'abilities', ['assault'],
    { en: 'IMPACT (X) Y', es: 'IMPACT (X) Y' },
    { en: 'After a successful Charge, each eligible fighting or supporting model rolls X dice; each Y+ gives an Armour Pool hit with Damage 1 and no Surge.', es: 'Tras una Carga exitosa, cada miniatura apta de las filas de combate o apoyo tira X dados; cada Y+ causa un impacto de Daño 1 sin Surge.' },
    { aliases: { en: ['impact hit'], es: ['impacto de carga'] }, relatedIds: ['fighting-rank', 'supporting-rank'] }),
  term('impassable-terrain', 86, 'terrain', ['movement'],
    { en: 'IMPASSABLE TERRAIN', es: 'Terreno infranqueable' },
    { en: 'Terrain without an Access Point to an adjacent elevation; models cannot cross, enter or finish overlapping it.', es: 'Terreno sin Punto de Acceso hacia una elevación contigua; las miniaturas no pueden cruzarlo, entrar en él ni acabar solapándolo.' },
    { relatedIds: ['access-point'] }),
  term('indirect-fire', 86, 'weapons', ['assault'],
    { en: 'INDIRECT FIRE', es: 'INDIRECT FIRE' },
    { en: 'A ranged weapon may target within Range without Line of Sight; a target not in sight may make an Evade roll.', es: 'Un arma a distancia puede atacar dentro de su alcance sin línea de visión; un objetivo no visible puede tirar Evasión.' },
    { aliases: { en: [], es: ['fuego indirecto'] }, relatedIds: ['line-of-sight', 'evade-roll'] }),
  term('instant', 86, 'weapons', ['assault'],
    { en: 'INSTANT', es: 'INSTANT' },
    { en: 'Enemy units cannot declare or resolve Reactions in response to attacks with this weapon.', es: 'Las unidades enemigas no pueden declarar ni resolver Reacciones contra ataques de esta arma.' },
    { aliases: { en: [], es: ['instantánea'] }, relatedIds: ['special-ability'] }),
  term('leading-model', 86, 'movement', ['movement', 'assault'],
    { en: 'LEADING MODEL', es: 'Miniatura líder' },
    { en: 'The model chosen as the movement reference; move it first, then place the unit’s other models in Coherency.', es: 'Miniatura elegida como referencia del movimiento; se mueve primero y después se coloca el resto de la unidad en Coherencia.' },
    { relatedIds: ['unit-coherency'] }),
  term('line-of-sight', 86, 'terrain', ['assault'],
    { en: 'LINE OF SIGHT (LoS)', es: 'Línea de visión (LdV)' },
    { en: 'A top-down line between bases determines visibility, with each intervening terrain piece checked under cover rules.', es: 'Una línea vista desde arriba entre peanas determina la visibilidad; cada terreno interpuesto se comprueba según las reglas de cobertura.' },
    { aliases: { en: ['LoS'], es: ['visión', 'LdV'] }, relatedIds: ['visible', 'blocking-terrain'] }),
  term('locked-in', 87, 'weapons', ['assault'],
    { en: 'LOCKED IN (X)', es: 'LOCKED IN (X)' },
    { en: 'Adds X Rate of Attack to a ranged weapon when its target, not the attacker, has STATIONARY.', es: 'Añade X de Cadencia de Ataque al arma a distancia si el objetivo, no el atacante, tiene STATIONARY.' },
    { aliases: { en: [], es: ['fijado'] }, relatedIds: ['stationary'] }),
  term('long-range', 87, 'weapons', ['assault'],
    { en: 'LONG RANGE (X)', es: 'LONG RANGE (X)' },
    { en: 'Extends maximum range to X inches. Attacking models beyond the weapon’s normal range suffer -1 to Hit.', es: 'Extiende el alcance máximo a X pulgadas. Las miniaturas que disparan más allá del alcance normal sufren -1 a Impacto.' },
    { aliases: { en: [], es: ['largo alcance'] } }),
  term('mid-ground', 87, 'terrain', ['movement', 'assault'],
    { en: 'MID GROUND', es: 'Nivel medio' },
    { en: 'Elevation on horizontal Size 1 or 2 terrain; engagement with another elevation needs a shared Access Point.', es: 'Elevación sobre terreno horizontal de Tamaño 1 o 2; trabarse con otro nivel requiere un Punto de Acceso compartido.' },
    { relatedIds: ['elevation-level', 'access-point'] }),
  term('mission-markers', 87, 'objectives', ['before-play', 'scoring-cleanup'],
    { en: 'MISSION MARKERS', es: 'Marcadores de misión' },
    { en: 'Numbered objectives placed during setup. Eligible nearby units contest them by Current Supply; control persists until the opponent exceeds that total.', es: 'Objetivos numerados colocados al preparar la mesa. Las unidades aptas cercanas los disputan con su Suministro Actual; el control persiste hasta que el rival supera ese total.' },
    { aliases: { en: ['objectives'], es: ['objetivos'] }, relatedIds: ['current-supply-value', 'victory-points'] }),
  term('modifier', 88, 'core', ['core-concepts'],
    { en: 'MODIFIER', es: 'Modificador' },
    { en: 'Changes a roll’s target number, not the die result: a positive modifier helps and a negative one hinders; the target stays between 2+ and 6+.', es: 'Altera el valor objetivo de una tirada, no el resultado del dado: el positivo ayuda y el negativo perjudica; el objetivo queda entre 2+ y 6+.' },
    { relatedIds: ['buff', 'debuff'] }),
  term('morph', 88, 'abilities', ['core-concepts'],
    { en: 'MORPH (Unit Name) X', es: 'MORPH (Nombre de unidad) X' },
    { en: 'With sufficient Available Supply, places the named model as a new, already-activated unit and removes X models from the source unit; lost Supply still awards VP.', es: 'Con Suministro Disponible suficiente, coloca la miniatura indicada como nueva unidad ya activada y retira X miniaturas de la original; el Suministro perdido concede PV.' },
    { aliases: { en: ['morphing'], es: ['transformar', 'metamorfosis'] }, relatedIds: ['available-supply', 'victory-points'], faqPage: 5 }),
  term('non-lethal-damage', 88, 'combat', ['assault', 'combat'],
    { en: 'NON-LETHAL DAMAGE (X)', es: 'Daño no letal (X)' },
    { en: 'Adds X to accumulated damage without removing models immediately; later standard damage combines with it. It can end SHIELDED.', es: 'Suma X al daño acumulado sin retirar miniaturas de inmediato; el daño normal posterior se combina con él. Puede acabar con SHIELDED.' },
    { relatedIds: ['shielded'] }),
  term('on-creep', 88, 'status', ['movement', 'assault'],
    { en: 'ON CREEP', es: 'Sobre Creep' },
    { en: 'A Ground Zerg unit within 6 inches of a Creep source has this keyword, enabling rules that require it.', es: 'Una unidad Zerg terrestre a 6 pulgadas o menos de una fuente de Creep obtiene esta palabra clave para activar reglas que la exigen.' },
    { aliases: { en: ['creep'], es: ['en creep'] } }),
  term('pierce', 88, 'weapons', ['assault', 'combat'],
    { en: 'PIERCE [TAG] X', es: 'PIERCE [ETIQUETA] X' },
    { en: 'Against a unit with the specified Combat Tag, use X as this weapon’s Damage value.', es: 'Contra una unidad con la Etiqueta de Combate indicada, usa X como Daño de esta arma.' },
    { aliases: { en: [], es: ['perforación'] }, relatedIds: ['combat-tags'] }),
  term('pinpoint', 88, 'weapons', ['assault'],
    { en: 'PINPOINT', es: 'PINPOINT' },
    { en: 'Allows a ranged attack to target an Engaged enemy unit despite the normal restriction.', es: 'Permite a un ataque a distancia elegir como objetivo una unidad enemiga trabada pese a la restricción habitual.' },
    { aliases: { en: [], es: ['precisión puntual'] }, relatedIds: ['engaged'] }),
  term('place', 88, 'movement', ['movement', 'assault'],
    { en: 'PLACE (X)', es: 'PLACE (X)' },
    { en: 'Relocates the Leading Model wholly within X inches and then sets the unit in Coherency. It ignores paths and elevation but must end legally; Assault placement may engage.', es: 'Recoloca la Miniatura Líder completamente dentro de X pulgadas y después el resto en Coherencia. Ignora rutas y elevación, pero debe acabar legalmente; en Asalto puede trabarse.' },
    { aliases: { en: ['placement'], es: ['colocar'] }, relatedIds: ['leading-model', 'unit-coherency'] }),
  term('precision', 88, 'weapons', ['assault', 'combat'],
    { en: 'PRECISION (X)', es: 'PRECISION (X)' },
    { en: 'After rolling to Hit, moves up to X failed attack dice to the Armour Pool as successful hits, including for Surge.', es: 'Tras tirar para Impactar, pasa hasta X dados fallidos a la Reserva de Armadura como impactos válidos, también para Surge.' },
    { aliases: { en: [], es: ['precisión'] }, relatedIds: ['surge'] }),
  term('ready', 88, 'army', ['before-play', 'scoring-cleanup'],
    { en: 'READY', es: 'Preparada' },
    { en: 'The face-up, usable state of a Tactical or Faction Card. Exhausted cards return to Ready during cleanup.', es: 'Estado boca arriba y utilizable de una Carta Táctica o de Facción. Las cartas agotadas vuelven a estar Preparadas durante la limpieza.' },
    { aliases: { en: ['ready card'], es: ['lista', 'carta preparada'] } }),
  term('repeatable', 88, 'abilities', ['core-concepts'],
    { en: 'REPEATABLE', es: 'REPEATABLE' },
    { en: 'Exempts an ability from its once-per-round limit when each cost and trigger is met. Reactions still obey the one-per-activation limit.', es: 'Exime a una habilidad del límite de una vez por ronda si cumple cada coste y condición. Las Reacciones siguen limitadas a una por activación.' },
    { aliases: { en: [], es: ['repetible'] }, relatedIds: ['special-ability'] }),
  term('reserves', 88, 'movement', ['before-play', 'movement'],
    { en: 'RESERVES', es: 'Reservas' },
    { en: 'The off-board area where all units start. Units there normally cannot be targeted, use abilities or contest objectives, and deploy when allowed.', es: 'Zona fuera del tablero donde empiezan todas las unidades. Allí normalmente no pueden ser objetivo, usar habilidades ni disputar objetivos; despliegan cuando se permite.' },
    { relatedIds: ['available-supply', 'entry-edge'] }),
  term('respawn', 89, 'abilities', ['core-concepts'],
    { en: 'RESPAWN (X)', es: 'RESPAWN (X)' },
    { en: 'Returns up to X destroyed models to a surviving unit, only in legal positions and without raising its Current Supply bracket.', es: 'Devuelve hasta X miniaturas destruidas a una unidad superviviente, solo en posiciones legales y sin subir su tramo de Suministro Actual.' },
    { aliases: { en: [], es: ['reaparición'] }, relatedIds: ['heal', 'current-supply-value'] }),
  term('shielded', 89, 'status', ['assault', 'combat'],
    { en: 'SHIELDED', es: 'SHIELDED' },
    { en: 'The Shield adds to the first model’s HP. This status ends when total assigned damage exceeds Shield or that model dies; HEAL cannot restore it.', es: 'El Escudo se suma a los puntos de vida (HP) de la primera miniatura. El estado termina si el daño total asignado supera el Escudo o muere esa miniatura; HEAL no lo restaura.' },
    { aliases: { en: ['shield'], es: ['escudo', 'protegida'] }, relatedIds: ['heal', 'non-lethal-damage'] }),
  term('sidearm', 89, 'weapons', ['assault', 'combat'],
    { en: 'SIDEARM', es: 'SIDEARM' },
    { en: 'Lets an equipped model attack with this weapon in addition to its normal weapon; resolve each sidearm in a separate Batch.', es: 'Permite a una miniatura atacar con esta arma además de la normal; cada arma secundaria se resuelve en un lote separado.' },
    { aliases: { en: [], es: ['arma secundaria'] }, relatedIds: ['batch'] }),
  term('siege-mode', 89, 'status', ['movement', 'assault', 'combat'],
    { en: 'SIEGE MODE', es: 'SIEGE MODE' },
    { en: 'Prevents moving, disengaging, running, charging and closing ranks. Only Siege Mode weapons may be used; returning to Reserves removes the status.', es: 'Impide mover, destrabarse, correr, cargar y cerrar filas. Solo pueden usarse armas del Modo Asedio; volver a Reservas retira el estado.' },
    { aliases: { en: [], es: ['modo asedio'] }, relatedIds: ['status', 'reserves'] }),
  term('special-ability', 89, 'abilities', ['core-concepts'],
    { en: 'SPECIAL ABILITY', es: 'Habilidad especial' },
    { en: 'A named card ability classed as Active, Passive or Reaction. Its use depends on timing, activation and its stated conditions.', es: 'Habilidad con nombre impresa en una carta, de tipo Activa, Pasiva o Reacción. Su uso depende del momento, la activación y sus condiciones.' },
    { relatedIds: ['repeatable', 'activation'] }),
  term('specialist', 89, 'weapons', ['before-play'],
    { en: 'SPECIALIST', es: 'SPECIALIST' },
    { en: 'Only one model in the unit may be equipped with this weapon.', es: 'Solo una miniatura de la unidad puede equiparse con esta arma.' },
    { aliases: { en: [], es: ['especialista'] } }),
  term('spillover', 89, 'weapons', ['assault'],
    { en: 'SPILLOVER', es: 'SPILLOVER' },
    { en: 'A template can hit additional units in separate Batches without inheriting the weapon’s keywords. With a primary target, these units must share its Combat Tag and elevation; a targetless ability template needs only shared elevation.', es: 'Una plantilla puede impactar a otras unidades en lotes separados sin heredar las palabras clave del arma. Si hay objetivo principal, deben compartir su Etiqueta de Combate y elevación; una plantilla de habilidad sin objetivo solo exige la misma elevación.' },
    { aliases: { en: [], es: ['daño colateral', 'rebose'] }, relatedIds: ['batch', 'combat-tags'], faqPage: 5 }),
  term('stationary', 90, 'status', ['movement', 'assault'],
    { en: 'STATIONARY', es: 'STATIONARY' },
    { en: 'All units gain this status at round start and lose it whenever one of their models moves, is moved or is PLACED.', es: 'Todas las unidades reciben este estado al comenzar la ronda y lo pierden si cualquiera de sus miniaturas se mueve, es movida o es colocada con PLACE.' },
    { aliases: { en: [], es: ['estacionaria', 'inmóvil'] }, relatedIds: ['locked-in'] }),
  term('status', 90, 'status', ['core-concepts'],
    { en: 'STATUS', es: 'Estado' },
    { en: 'A condition or mode affecting a unit. Statuses generally persist through cleanup until their own removal condition occurs.', es: 'Condición o modo que afecta a una unidad. Los estados suelen continuar tras la limpieza hasta que se cumple su condición de retirada.' },
    { relatedIds: ['stay-in-play', 'burrowed', 'siege-mode'] }),
  term('stay-in-play', 90, 'status', ['scoring-cleanup'],
    { en: 'STAY IN PLAY', es: 'STAY IN PLAY' },
    { en: 'A token, marker or effect that survives Cleanup & Refresh until a specific rule or event removes it.', es: 'Ficha, marcador o efecto que permanece durante Limpieza y Renovación hasta que una regla o suceso concreto lo retira.' },
    { aliases: { en: [], es: ['permanece en juego'] }, relatedIds: ['status'] }),
  term('summon', 90, 'abilities', ['core-concepts'],
    { en: 'SUMMON (Unit Name)', es: 'SUMMON (Nombre de unidad)' },
    { en: 'With enough Available Supply, places a new unit beside its parent outside enemy Engagement Range and Zone of Influence; activation follows the parent in later phases.', es: 'Con Suministro Disponible suficiente, coloca una unidad junto a su unidad madre fuera del Alcance enemigo y de su Zona de Influencia; en fases posteriores se activa tras ella.' },
    { aliases: { en: ['summoned'], es: ['invocar', 'invocación'] }, relatedIds: ['available-supply', 'zone-of-influence'] }),
  term('supply-value', 90, 'army', ['before-play', 'movement', 'scoring-cleanup'],
    { en: 'SUPPLY VALUE', es: 'Valor de Suministro' },
    { en: 'The Supply Profile value for the unit’s model count. Its starting value sets Army Slot use; its current value changes with losses and affects deployment and scoring.', es: 'Valor del Perfil de Suministro según las miniaturas de la unidad. El inicial fija los espacios de ejército; el actual cambia con las bajas y afecta despliegue y puntuación.' },
    { relatedIds: ['current-supply-value', 'army-slot'] }),
  term('supporting-rank', 90, 'combat', ['combat'],
    { en: 'SUPPORTING RANK', es: 'Fila de apoyo' },
    { en: 'A model in base contact with a same-unit Fighting Rank model but outside enemy Engagement Range; it may still strike in the Combat Phase.', es: 'Miniatura en contacto con una de su unidad situada en Fila de Combate, aunque fuera del Alcance enemigo; aun así puede atacar en Combate.' },
    { relatedIds: ['fighting-rank', 'engagement-range'] }),
  term('tactical-mass', 90, 'combat', ['movement', 'assault'],
    { en: 'TACTICAL MASS', es: 'Masa táctica' },
    { en: 'A unit has it when its Current Supply exceeds the combined Current Supply of enemies it is Engaged with; it avoids the usual post-Disengage penalty.', es: 'Se tiene si el Suministro Actual propio supera la suma del de los enemigos trabados; evita la penalización habitual tras Destrabarse.' },
    { relatedIds: ['current-supply-value', 'engaged'] }),
  term('tough', 90, 'status', ['assault', 'combat'],
    { en: 'TOUGH (X)', es: 'TOUGH (X)' },
    { en: 'Turns up to X failed Armour rolls into successes, preventing those dice from reaching the Damage Pool.', es: 'Convierte hasta X tiradas fallidas de Armadura en éxitos, impidiendo que esos dados lleguen a la Reserva de Daño.' },
    { aliases: { en: [], es: ['resistente'] } }),
  term('unengaged', 91, 'combat', ['movement', 'assault'],
    { en: 'UNENGAGED', es: 'No trabada' },
    { en: 'A Ground unit with no valid enemy Ground engagement; Flying units are always Unengaged.', es: 'Unidad terrestre sin enfrentamiento válido con otra terrestre enemiga; las unidades voladoras siempre están no trabadas.' },
    { relatedIds: ['engaged', 'flying'] }),
  term('visible', 91, 'terrain', ['assault'],
    { en: 'VISIBLE', es: 'Visible' },
    { en: 'A model can be seen through a valid Line of Sight trace after cover and HIDDEN restrictions are applied.', es: 'Una miniatura se puede ver si existe una Línea de Visión válida tras aplicar cobertura y restricciones de HIDDEN.' },
    { relatedIds: ['line-of-sight', 'hidden'] }),
  term('wholly-within', 91, 'core', ['core-concepts'],
    { en: 'WHOLLY WITHIN', es: 'Completamente dentro' },
    { en: 'The entire base must lie inside the stated distance; for a unit, every model must qualify.', es: 'La peana entera debe quedar dentro de la distancia indicada; para una unidad, deben cumplirlo todas sus miniaturas.' },
    { relatedIds: ['within', 'unit-coherency'] }),
  term('within', 91, 'core', ['core-concepts'],
    { en: 'WITHIN', es: 'Dentro de' },
    { en: 'Any part of a model’s base touching the specified range is enough; a unit qualifies if at least one model does.', es: 'Basta con que parte de la peana toque el alcance indicado; una unidad cumple si lo hace al menos una miniatura.' },
    { relatedIds: ['wholly-within'] }),
  term('zone-of-influence', 91, 'movement', ['before-play', 'movement'],
    { en: 'ZONE OF INFLUENCE', es: 'Zona de influencia' },
    { en: 'A 6-inch area inward from the primary Entry Edge. Units arriving from Reserves cannot finish their arrival in the opponent’s zone.', es: 'Área de 6 pulgadas desde el Borde de Entrada principal. Las unidades que llegan desde Reservas no pueden terminar allí si es la zona rival.' },
    { relatedIds: ['entry-edge', 'reserves'] }),

  // Basic concepts used repeatedly in the game sequence but absent from Part 11.
  term('activation', 54, 'core', ['movement', 'assault', 'combat'],
    { en: 'Activation', es: 'Activación' },
    { en: 'A turn in which one eligible unit is chosen to act; the allowed action depends on the current phase.', es: 'Turno en el que se elige una unidad apta para actuar; la acción disponible depende de la fase actual.' },
    { section: '8.2', relatedIds: ['active-player', 'pass'] }),
  term('pass', 55, 'core', ['movement', 'assault'],
    { en: 'Pass', es: 'Pasar' },
    { en: 'Decline an activation for the rest of the phase. The first player to Pass receives the First Player Marker for the next phase.', es: 'Renunciar a seguir activando durante esa fase. Quien pasa primero recibe el Marcador de Primer Jugador de la siguiente fase.' },
    { section: '8.2.1', relatedIds: ['activation', 'first-player-marker'] }),
  term('unit-coherency', 35, 'movement', ['movement', 'assault', 'scoring-cleanup'],
    { en: 'Unit Coherency', es: 'Coherencia de unidad' },
    { en: 'After repositioning, models must be wholly within 3 inches of the Leading Model and connected by legal Coherency Links; casualties alone do not recheck it.', es: 'Tras recolocarse, las miniaturas deben estar completamente dentro de 3 pulgadas de la Líder y conectadas por enlaces válidos; las bajas solas no obligan a recomprobarla.' },
    { section: '4.4', relatedIds: ['leading-model', 'wholly-within'] }),
  term('supply-pool', 55, 'army', ['movement'],
    { en: 'Supply Pool', es: 'Reserva de Suministro' },
    { en: 'The maximum combined Current Supply allowed on the battlefield; it grows by round and is unlimited in the final round.', es: 'Máximo Suministro Actual conjunto permitido en mesa; aumenta por rondas y no tiene límite en la última.' },
    { section: '8.3.1', relatedIds: ['available-supply', 'current-supply-value'] }),
  term('batch', 61, 'combat', ['assault', 'combat'],
    { en: 'Attack Batch', es: 'Lote de ataque' },
    { en: 'One attack group resolved through Hit, Surge, Armour, Evade and Damage steps before the next group.', es: 'Grupo de ataques que se resuelve mediante Impacto, Surge, Armadura, Evasión y Daño antes de pasar al siguiente.' },
    { section: '8.7.4', aliases: { en: ['batch'], es: ['lote'] }, relatedIds: ['surge', 'evade-roll'] }),
  term('surge', 62, 'combat', ['assault', 'combat'],
    { en: 'Surge', es: 'Surge' },
    { en: 'If the weapon’s Surge Type matches a target Combat Tag, its Surge die moves successful Hit dice past Armour into the Damage Pool.', es: 'Si el Tipo de Surge del arma coincide con una Etiqueta de Combate del objetivo, su dado Surge pasa impactos más allá de Armadura hacia Daño.' },
    { section: '8.7.4', relatedIds: ['combat-tags', 'batch'] }),
  term('evade-roll', 62, 'combat', ['assault', 'combat'],
    { en: 'Evade Roll', es: 'Tirada de Evasión' },
    { en: 'An eligible defender rolls the Damage Pool and removes dice meeting its Evade target number before damage is assigned.', es: 'Un defensor apto tira los dados de la Reserva de Daño y retira los que alcancen su valor de Evasión antes de asignar el daño.' },
    { section: '8.7.4', relatedIds: ['hidden', 'anti-evade'] }),
  term('victory-points', 72, 'objectives', ['scoring-cleanup'],
    { en: 'Victory Points (VP)', es: 'Puntos de Victoria (PV)' },
    { en: 'The score earned from the Mission Card’s conditions and other applicable rules; the higher final total wins unless another winning condition applies.', es: 'Puntuación obtenida por las condiciones de la Carta de Misión y otras reglas; gana el total final mayor salvo condición de victoria diferente.' },
    { section: '8.9.2', aliases: { en: ['VP'], es: ['PV'] }, relatedIds: ['mission-markers'] }),
];
